baseURL: https://unthaitled.org
languageCode: en-us
title: un.thai.tled | collective of Thai creatives in Berlin
theme: 
  - hugo-fresh

params:
  description:
    > 
      We organise events to showcase talents from Thailand and in Germany; to free ourselves from easy labels and stereotypes; to bring the narrative back to our hands.
  navbarlogo:
   image: logos/normal.svg
   link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    title: un.thai.tled
    subtitle:
      > 
        Collective of Thai creatives in Berlin. We organise events to showcase talents from Thailand and in Germany; to free ourselves from easy labels and stereotypes; to bring the narrative back to our hands.

    buttontext: Who are we?
    buttonlink: "#about"
    image: hero-banner.png
  navbar:
  - title: Thai Creatives Database
    url: /thai-creatives-in-germany
  - title: Team
    url: /#team
  - title: Event
    url: https://www.facebook.com/unthaitled
  - title: About
    url: /#about
  section3:
    title: What is un.thai.tled?
    subtitle:
      > 
        We are a group of Thai creatives in Germany - not only we
        encounter misconceptions and stereotypes within western
        world, and their unconscious ignorance - but also the lack
        of socio-cultural engagement between Thai and German people. 


        Therefore our mission is to provide platform or opportunities 
        for the creatives talents, with focus specifically on people from
        Thailand/with Thai cultural-biological background - which
        would lead to further collaboration/exchange projects between
        people  - and through these we would be able to educate/inform/
        evoke discussions amongst audiences about
        certain topics related to Thailand, or being Thai. Because we are
        the ‘untitled’, we wish to be freed from titles and easy labels
        people tend to put on us. 


        Now it’s time for you to listen carefully. We will organize series of events that focus on specific
        medias, such as film or music, with interdisciplinary approach
        (design + arts + academics) and intermedial aspect


        And by the word “Thai”, we are by no means excluding ourselves 
        from other cultural exchange events in Berlin - which we would
        love to be in partnership with. We only make it clear, that our 
        project “Un-Thai-Tled” focuses fore-mostly on creatives from 
        Thailand / with Thai cultural-biological background.


        For 2019 we will organize 3 official film screenings and 1 cultural evening.
    image: showcase.png
  section4:
    title: Meet The Team
  footer:
    logo: logo-white-alt.svg
    socialmedia:
    - link: https://www.facebook.com/unthaitled/
      icon: facebook
    - link: https://www.instagram.com/unthaitled/
      icon: instagram